import React from 'react';
import Link from 'next/link';

export default function TermsAndConditionsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto flex h-14 items-center px-4 md:px-6">
          <Link className="flex items-center space-x-2 font-bold" href="/">
            <span>Content Shop</span>
          </Link>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8 md:px-6 md:py-12 max-w-4xl">
        <h1 className="text-3xl font-bold tracking-tight mb-8">Terms and Conditions</h1>
        
        <div className="space-y-6 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Introduction</h2>
            <p>
              Welcome to Content Shop. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Use of Service</h2>
            <p>
              Content Shop provides AI-powered content generation tools for e-commerce businesses. You are responsible for all content generated and used in connection with your account. You agree not to use the service for any illegal or unauthorized purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. User Accounts</h2>
            <p>
              To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Intellectual Property</h2>
            <p>
              The content generated by our AI tools is provided to you for your business use. However, Content Shop retains all rights to the underlying technology, software, and intellectual property that powers the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Payment, Subscription, and Refunds</h2>
            <p>
              Some features of the service may require payment. By selecting a paid plan, you agree to pay the fees associated with that plan. Prices and subscription terms are subject to change with notice.
            </p>
            <p className="mt-2">
              For details on our refund policy, please refer to our <Link href="/refund-policy" className="underline hover:text-primary">Refund Policy</Link> page.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Limitation of Liability</h2>
            <p>
              Content Shop is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Your continued use of the service after any changes indicates your acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Contact Us</h2>
            <p>
              If you have any questions about these Terms and Conditions, please contact us at [email protected].
            </p>
          </section>
          
          <p className="text-sm pt-4">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </main>
      
      <footer className="border-t py-6 md:py-0">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row px-4">
          <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
            Built for e-commerce brands. © {new Date().getFullYear()} Content Shop.
          </p>
        </div>
      </footer>
    </div>
  );
}

